// <auto-generated />
namespace TheUnitGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateAddressLine2ColumnInAddressTableTypo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateAddressLine2ColumnInAddressTableTypo));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251058312_UpdateAddressLine2ColumnInAddressTableTypo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
